[package]
name = "hills"
version = "0.1.0"
edition = "2021"

[dependencies]
sled = "0.34"
rkyv = { workspace = true }
chrono = { version = "0.4", features = ["rkyv"] }
thiserror = "1.0"
log = "0.4"

hills-base = { path = "../hills-base" }
hills-derive = { path = "../hills-derive" }
