[workspace]
resolver = "2"
members = [
	"hills",
	"hills_base",
	"hills_derive",
	"hills_server"
]

[workspace.dependencies]
rkyv = { version = "0.7.42", features = ["validation", "strict"] }
chrono = { version = "0.4", features = [] }
