[package]
name = "hills_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35", features = ["rt", "net"] }
anyhow = "1.0"
hills = { path = "../hills" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "ansi", "time", "local-time"] }

