[package]
name = "hills_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["extra-traits"] }
quote = "1.0"
proc-macro-error = "1.0"

[dev-dependencies]
hills_base = { path = "../hills_base" }